import { getRunData, getAllRuns, getAllRunsV18 } from "$lib/server/data";
import fs from "node:fs";
import path from "node:path";
import { compile } from "mdsvex";

export const prerender = true;

function convertEmojisToUnicode(content: string): string {
  return content
    .replace(/\u2705/g, "\u2714") // white heavy check mark -> heavy check mark
    .replace(/\u274C/g, "\u2718") // cross mark -> heavy ballot X
    .replace(/\u26A0\uFE0F/g, "\u26A0") // warning sign with variation selector -> warning sign
    .replace(/\u{1F6A7}/gu, "\u26A0"); // construction sign -> warning sign
}

export function entries() {
  const legacyEntries = getAllRuns().map((run) => ({ id: run.id }));
  const v18Entries = getAllRunsV18().map((run) => ({ id: run.id }));
  return [...legacyEntries, ...v18Entries];
}

function resolveRunDataDir(runId: string): string {
  const legacyPath = path.join(process.cwd(), "eval-results", runId);
  if (fs.existsSync(legacyPath)) return "eval-results";
  const v18Path = path.join(process.cwd(), "v1.8-results", runId);
  if (fs.existsSync(v18Path)) return "v1.8-results";
  throw new Error(`Run ID ${runId} not found in any results directory`);
}

export const load = async ({ params }: { params: { id: string } }) => {
  const dataDir = resolveRunDataDir(params.id);
  const fullDataDir = path.join(process.cwd(), dataDir);
  const run = getRunData(params.id, fullDataDir);

  // Read report.md
  const reportPath = path.join(
    process.cwd(),
    dataDir,
    params.id,
    "report.md",
  );
  let reportContent = "";
  let compiledReport = null;

  if (fs.existsSync(reportPath)) {
    reportContent = convertEmojisToUnicode(
      fs.readFileSync(reportPath, "utf-8"),
    );
    // Compile markdown to HTML/Svelte code server-side
    // Note: mdsvex.compile returns { code, data, map }
    // But we need to render this code on the client.
    // If we treat it as just HTML, we lose Svelte components (if any were used).
    // Since report.md is generated by the harness, it's likely standard markdown.
    // So compiling to HTML string is safer for "dynamic" content than treating as a component module.
    // However, I proposed "Obsidian" styling which relies on classes.

    // Better approach: Use a runtime markdown renderer like 'marked' or 'svelte-markdown' for this specific dynamic file,
    // OR compile it here and send the HTML.
    // Let's use compile() from mdsvex to get the HTML with the syntax highlighting classes.

    try {
      // We need to pass the config to get highlighting
      // Importing the config from svelte.config.js might be tricky in ESM.
      // Let's define minimal config here or rely on the fact that we just want HTML.

      // Re-importing rehype plugins locally
      const { default: rehypePrettyCode } = await import("rehype-pretty-code");

      compiledReport = await compile(reportContent, {
        rehypePlugins: [
          [
            rehypePrettyCode,
            { theme: "catppuccin-macchiato", keepBackground: true },
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
          ] as any,
        ],
      });
    } catch (e) {
      console.error("Markdown compile error:", e);
    }
  }

  return {
    run,
    reportHtml: compiledReport?.code || "",
  };
};
