import { getRunData, getAllRuns } from '$lib/server/data';
import fs from 'node:fs';
import path from 'node:path';
import { error } from '@sveltejs/kit';
import { compile } from 'mdsvex';
import mdsvexConfig from '../../../../svelte.config.js'; // Hacky import, or reuse config

export const prerender = true;

export function entries() {
    return getAllRuns().map(run => ({ id: run.id }));
}

export const load = async ({ params }) => {
    const run = getRunData(params.id);
    
    // Read report.md
    const reportPath = path.join(process.cwd(), 'eval-results', params.id, 'report.md');
    let reportContent = '';
    let compiledReport = null;

    if (fs.existsSync(reportPath)) {
        reportContent = fs.readFileSync(reportPath, 'utf-8');
        // Compile markdown to HTML/Svelte code server-side
        // Note: mdsvex.compile returns { code, data, map }
        // But we need to render this code on the client.
        // If we treat it as just HTML, we lose Svelte components (if any were used).
        // Since report.md is generated by the harness, it's likely standard markdown.
        // So compiling to HTML string is safer for "dynamic" content than treating as a component module.
        // However, I proposed "Obsidian" styling which relies on classes.
        
        // Better approach: Use a runtime markdown renderer like 'marked' or 'svelte-markdown' for this specific dynamic file,
        // OR compile it here and send the HTML.
        // Let's use compile() from mdsvex to get the HTML with the syntax highlighting classes.
        
        try {
            // We need to pass the config to get highlighting
            // Importing the config from svelte.config.js might be tricky in ESM.
            // Let's define minimal config here or rely on the fact that we just want HTML.
            
            // Re-importing rehype plugins locally
            const { default: rehypePrettyCode } = await import('rehype-pretty-code');
            
            compiledReport = await compile(reportContent, {
                rehypePlugins: [
                    [rehypePrettyCode, { theme: 'catppuccin-macchiato', keepBackground: true }]
                ]
            });
        } catch (e) {
            console.error('Markdown compile error:', e);
        }
    }

    return {
        run,
        reportHtml: compiledReport?.code || ''
    };
};
